# Generated by Django 2.2.6 on 2019-10-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='pub_fecha',
            new_name='pub_date',
        ),
    ]
