# Generated by Django 2.2.6 on 2019-10-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20191031_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='votos',
        ),
        migrations.AddField(
            model_name='opcion',
            name='correcto',
            field=models.BooleanField(default=False),
        ),
    ]
